# AppVeyor file
#   for Docker Machine Driver Sakuracloud

version: '{build}'

install:
  - ps: |
      Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version;
      $PSVersionTable;
      git --version;

build_script:
  - ps: |
      $version          = ((Invoke-RestMethod https://api.github.com/repos/sacloud/docker-machine-sakuracloud/releases/latest)[0] -split ";" | Select-String "tag_name=").ToString().Trim().Replace("tag_name=v", "");
      $appVeyorVersion  = $version + "." + ${env:APPVEYOR_BUILD_VERSION};
      $versionText      = "docker-machine-sakuracloud version Ver." + $version;
      echo $versionText;
      $versionText      = "package version Ver." + $appVeyorVersion;
      echo $versionText;
      $url32            = 'https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v' + $version + '/docker-machine-driver-sakuracloud_windows-386.zip';
      $url64            = 'https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v' + $version + '/docker-machine-driver-sakuracloud_windows-amd64.zip';
      Invoke-WebRequest $url32 -OutFile .\x32.zip;
      Invoke-WebRequest $url64 -OutFile .\x64.zip;
      $hash32           = (Get-FileHash .\x32.zip -Algorithm SHA512).Hash;
      $hash64           = (Get-FileHash .\x64.zip -Algorithm SHA512).Hash;
      Set-Location -Path .\docker-machine-sakuracloud;
      (Get-Content '.\docker-machine-sakuracloud.nuspec' -Raw).Replace("__VERSION__", "$($appVeyorVersion)") | Out-File '.\docker-machine-sakuracloud.nuspec';
      (Get-Content '.\tools\chocolateyinstall.ps1' -Raw).Replace("__VERSION__", "v$($version)").Replace("__HASH32__", $hash32).Replace("__HASH64__", $hash64) | Out-File '.\tools\chocolateyinstall.ps1';
      choco pack;

test_script:
  - ps: |
      $packName = 'docker-machine-sakuracloud';
      choco install $packName -s .\ -f;

artifacts:
  - path: '.\docker-machine-sakuracloud\*.nupkg'
  - path: '.\docker-machine-sakuracloud\tools\*.ps1'
  - path: '.\docker-machine-sakuracloud\*.nuspec'

#deploy_script:
#  - ps: |
#      $packName = 'docker-machine-sakuracloud';
#      choco apikey --key ${env:CHOCO_API_KEY} --source https://push.chocolatey.org/
#      choco push $nupkgName --source https://push.chocolatey.org/
